#!/bin/bash -e
cd $(dirname $0)
PATH=$HOME/gopath/bin:$GOPATH/bin:$PATH

if ! type -p dep; then
  echo go get github.com/golang/dep/cmd/dep
  go get github.com/golang/dep/cmd/dep
fi

if ! type -p goveralls; then
  echo go get github.com/mattn/goveralls
  go get github.com/mattn/goveralls
fi

[ -d vendor/github.com/spf13/afero ] || dep ensure
go test -v -covermode=count -coverprofile=cover.out .
go tool cover -func=cover.out
[ -z "$COVERALLS_TOKEN" ] || goveralls -coverprofile=cover.out -service=travis-ci -repotoken $COVERALLS_TOKEN
rm cover.out
