#!/bin/bash -e
cd "$(dirname $0)"
PATH=$HOME/go/bin:$PATH
unset GOPATH
export GO111MODULE=on

function announce
{
  echo
  echo $@
}

function v
{
  announce $@
  $@
}

if ! type -p goveralls; then
  v go install github.com/mattn/goveralls
fi

if ! type -p goreturns; then
  v go install github.com/sqs/goreturns
fi

go test -v -covermode=count -coverprofile=cover.out .
go tool cover -func=cover.out
[ -z "$COVERALLS_TOKEN" ] || goveralls -coverprofile=cover.out -service=travis-ci -repotoken $COVERALLS_TOKEN || echo 'Coult not push to coveralls'
rm cover.out

v goreturns -l -w *.go */*.go

v go vet ./...
